version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Adjust the port as necessary
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Adjust the port as necessary
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

  db:
    image: mongo:latest  # Use the appropriate database image
    ports:
      - "27017:27017"  # Adjust the port as necessary
    volumes:
      - db_data:/data/db

volumes:
  db_data:

