name: CI/CD for Node.js Application (FE and BE)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 4: Build Backend Docker image
    - name: Build Backend Docker image
      run: |
        docker build -t my-backend-app:latest ./backend

    # Step 5: Build Frontend Docker image
    - name: Build Frontend Docker image
      run: |
        docker build -t my-frontend-app:latest ./frontend

    # Step 7: Set up kind (Kubernetes in Docker) cluster
    - name: Set up kind cluster
      uses: helm/kind-action@v1.3.0
      with:
        version: v0.11.1  # You can specify the kind version here

    # Step 8: Load the backend Docker image into the kind cluster
    - name: Load Backend Image into Kind
      run: |
        kind load docker-image my-backend-app:latest

    # Step 9: Load the frontend Docker image into the kind cluster
    - name: Load Frontend Image into Kind
      run: |
        kind load docker-image my-frontend-app:latest

    # Step 10: Apply Kubernetes manifests
    - name: Deploy Backend to Kubernetes
      run: |
        kubectl apply -f k8s/backend-deployment.yaml

    - name: Deploy Frontend to Kubernetes
      run: |
        kubectl apply -f k8s/frontend-deployment.yaml

    # Step 11: Check if pods are running
    - name: Verify Kubernetes Deployment
      run: |
        kubectl get pods -o wide
